# Generated by Django 4.2.1 on 2023-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_category_colorvariant_product_sizevariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_brand",
            field=models.CharField(
                blank=True, default="Unknown Brand", max_length=100, null=True
            ),
        ),
    ]
