# Generated by Django 4.2.1 on 2023-06-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_cart_cartitems"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitems", name="cart",),
        migrations.RemoveField(model_name="cartitems", name="color_variant",),
        migrations.RemoveField(model_name="cartitems", name="product",),
        migrations.RemoveField(model_name="cartitems", name="size_variant",),
        migrations.DeleteModel(name="Cart",),
        migrations.DeleteModel(name="CartItems",),
    ]
