# Generated by Django 4.2.1 on 2023-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0012_alter_cart_options_alter_cartitems_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="cart", options={},),
        migrations.AlterModelOptions(name="cartitems", options={},),
        migrations.AlterModelOptions(name="category", options={},),
        migrations.AlterModelOptions(name="colorvariant", options={},),
        migrations.AlterModelOptions(name="product", options={},),
        migrations.AlterModelOptions(name="sizevariant", options={},),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product"),
        ),
    ]
