# Generated by Django 4.2.1 on 2023-06-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0014_alter_cart_options_alter_cartitems_options_and_more"),
    ]

    operations = []
