# Generated by Django 4.2.1 on 2023-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0015_auto_20230626_0034"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_link",
            field=models.URLField(default="your_default_image_link"),
        ),
    ]
