# Generated by Django 4.2.1 on 2023-06-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0017_category_image_link_alter_category_category_image"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductImage",),
    ]
