# Generated by Django 4.2.1 on 2023-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0019_product_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.RemoveField(model_name="product", name="image_link",),
        migrations.AddField(
            model_name="product",
            name="image_links",
            field=models.ManyToManyField(
                blank=True, default="your_default_image_link", to="login.image"
            ),
        ),
    ]
