# Generated by Django 4.2.1 on 2023-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0021_remove_product_image_links_product_image_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image_link",),
        migrations.AddField(
            model_name="product",
            name="image_urls",
            field=models.TextField(blank=True, default=""),
        ),
    ]
