# Generated by Django 4.2.1 on 2023-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0022_remove_product_image_link_product_image_urls"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image_urls",),
        migrations.AddField(
            model_name="product",
            name="image_link",
            field=models.URLField(default="your_default_image_link"),
        ),
    ]
