# Generated by Django 4.2.1 on 2023-06-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0023_remove_product_image_urls_product_image_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="is_paid",),
        migrations.RemoveField(model_name="cart", name="user",),
    ]
