# Generated by Django 4.2.1 on 2023-06-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0025_cart_is_paid_cart_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="sizevariant", name="price",),
    ]
