# Generated by Django 4.2.1 on 2023-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0026_remove_sizevariant_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizevariant",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
